export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
//
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
//
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
//
export const LOAD_AUTHENTICATION_DATA = 'LOAD_AUTHENTICATION_DATA';
//
export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAILURE = 'POST_FAILURE';
//
export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST';
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS';
export const GET_ALL_POST_FAIL = 'GET_ALL_POST_FAIL';
//
export const APPROVE_REQUEST = 'APPROVE_REQUEST';
export const APPROVE_SUCCESS = 'APPROVE_SUCCESS';
export const APPROVE_FAIL = 'APPROVE_FAIL';
//
export const GET_HOME_POST_REQUEST = 'GET_HOME_POST_REQUEST';
export const GET_HOME_POST_SUCCESS = 'GET_HOME_POST_SUCCESS';
export const GET_HOME_POST_FAIL = 'GET_HOME_POST_FAIL';
//
export const GET_POST_DETAIL_REQUEST = 'GET_POST_DETAIL_REQUEST';
export const GET_POST_DETAIL_SUCCESS = 'GET_POST_DETAIL_SUCCESS';
export const GET_POST_DETAIL_FAIL = 'GET_POST_DETAIL_FAIL';
//
export const GET_HOME_BOOK_REQUEST = 'GET_HOME_BOOK_REQUEST';
export const GET_HOME_BOOK_SUCCESS = 'GET_HOME_BOOK_SUCCESS';
export const GET_HOME_BOOK_FAIL = 'GET_HOME_BOOK_FAIL';
//
export const GET_BOOK_DETAIL_REQUEST = 'GET_POST_DETAIL_REQUEST';
export const GET_BOOK_DETAIL_SUCCESS = 'GET_POST_DETAIL_SUCCESS';
export const GET_BOOK_DETAIL_FAIL = 'GET_POST_DETAIL_FAIL';
//
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_CART = 'REMOVE_CART';
//
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';
//
export const CONFIRM_ORDER = 'CONFIRM_ORDER';
